export const ENUMLIST = [
    {
        key:"DIGITAL_DEVICES",
        value:"디지털기기"
    },
    {
        key:"FURNITURE",
        value:"가구"
    },
    {
        key:"BABY_PRODUCTS",
        value:"아동물품"
    },
    {
        key:"CLOTHING",
        value:"옷"
    },
    {
        key:"ELECTRONICS",
        value:"전자물품"
    },
    {
        key:"HOME_KITCHEN",
        value:"주방물품"
    },
    {
        key:"SPORTS_LEISURE",
        value:"스포츠물품"
    },
    {
        key:"BEAUTY",
        value:"화장품"
    },
    {
        key:"PLANTS",
        value:"꽃"
    },
    {
        key:"PROCESSED_FOODS",
        value:"밀키트"
    },
    {
        key:"HEALTH_SUPPLEMENTS",
        value:"헬스도구"
    },
    {
        key:"BOOKS",
        value:"책"
    },
    {
        key:"OTHERS",
        value:"나머지"
    },
]